### ISSUE TITLE
If I connect a hotkey to a script filter, nothing gets shown

### ISSUE THREAD

**Issue by nikitavoloboev** [willfarrell/alfred-youtube-workflow#7]
For example : 

![2017-02-08 at 16 25](https://cloud.githubusercontent.com/assets/6391776/22743674/2ed8c8e8-ee1b-11e6-8c44-475081958941.png)

And nothing happens when I trigger it : 

![2017-02-08 at 16 25](https://cloud.githubusercontent.com/assets/6391776/22743692/395ec484-ee1b-11e6-87cb-2adabd3f17dd.png)

Thank you for any help.

**Comment by nikitavoloboev** [comment]
I suppose the answer is this : https://github.com/willfarrell/alfred-youtube-workflow/issues/6 

Apologise for starting a new issue.

**Comment by willfarrell** [comment]
Yeah ... It's cool. If you'd like to create a PR, I'd love to merge it. I have no problem making others contributors.

**Comment by willfarrell** [comment]
https://github.com/willfarrell/alfred-youtube-workflow/issues/6#issuecomment-279269194
